import Navegation from "./components/Navegation";
import "./globals.css";
import { Open_Sans } from "next/font/google";

const opensan = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={opensan.className}>
        <header>
          <Navegation/>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
